---
name: Data-Find
version: 0.02
author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: Find data in arbitrary data structures
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Data-Find
  license: http://dev.perl.org/licenses/
  repository: https://svn.hexten.net/andy/Perl/Data-Find/trunk
requires:
  Data::Dumper: 0
  Scalar::Util: 0
  Test::More: 0
provides:
  Data::Find:
    file: lib/Data/Find.pm
    version: 0.02
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
